{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sport\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "us\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "health\n",
      "world\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "us\n",
      "us\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "sport\n",
      "world\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "sport\n",
      "world\n",
      "world\n",
      "sport\n",
      "us\n",
      "world\n",
      "sci_tech\n",
      "sport\n",
      "health\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "entertainment\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "sport\n",
      "business\n",
      "sport\n",
      "us\n",
      "business\n",
      "us\n",
      "us\n",
      "us\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "business\n",
      "world\n",
      "health\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "entertainment\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "world\n",
      "health\n",
      "health\n",
      "business\n",
      "world\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "health\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "health\n",
      "world\n",
      "world\n",
      "sport\n",
      "business\n",
      "us\n",
      "us\n",
      "world\n",
      "sport\n",
      "health\n",
      "business\n",
      "sport\n",
      "sport\n",
      "world\n",
      "world\n",
      "us\n",
      "sport\n",
      "us\n",
      "world\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "entertainment\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "business\n",
      "us\n",
      "entertainment\n",
      "health\n",
      "business\n",
      "sport\n",
      "us\n",
      "sport\n",
      "sport\n",
      "us\n",
      "world\n",
      "sport\n",
      "us\n",
      "world\n",
      "business\n",
      "business\n",
      "business\n",
      "sport\n",
      "us\n",
      "sport\n",
      "sport\n",
      "health\n",
      "business\n",
      "business\n",
      "world\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "health\n",
      "sport\n",
      "business\n",
      "sport\n",
      "business\n",
      "business\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "us\n",
      "business\n",
      "world\n",
      "business\n",
      "business\n",
      "business\n",
      "sport\n",
      "world\n",
      "us\n",
      "sport\n",
      "world\n",
      "sport\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "business\n",
      "world\n",
      "sport\n",
      "sport\n",
      "us\n",
      "world\n",
      "sport\n",
      "us\n",
      "sport\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "business\n",
      "health\n",
      "business\n",
      "world\n",
      "entertainment\n",
      "world\n",
      "entertainment\n",
      "entertainment\n",
      "entertainment\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "sci_tech\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "sci_tech\n",
      "sport\n",
      "sci_tech\n",
      "business\n",
      "business\n",
      "us\n",
      "world\n",
      "business\n",
      "business\n",
      "health\n",
      "world\n",
      "us\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "business\n",
      "sport\n",
      "us\n",
      "sport\n",
      "business\n",
      "us\n",
      "health\n",
      "entertainment\n",
      "sport\n",
      "health\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "us\n",
      "sport\n",
      "health\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "us\n",
      "us\n",
      "business\n",
      "sci_tech\n",
      "world\n",
      "health\n",
      "sport\n",
      "world\n",
      "sport\n",
      "us\n",
      "business\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "business\n",
      "sport\n",
      "world\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "sport\n",
      "world\n",
      "world\n",
      "business\n",
      "us\n",
      "sci_tech\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "world\n",
      "sport\n",
      "health\n",
      "world\n",
      "us\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "entertainment\n",
      "world\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "world\n",
      "world\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "business\n",
      "business\n",
      "entertainment\n",
      "business\n",
      "sport\n",
      "sport\n",
      "health\n",
      "sport\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "sci_tech\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "business\n",
      "business\n",
      "sci_tech\n",
      "business\n",
      "world\n",
      "business\n",
      "world\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "business\n",
      "world\n",
      "world\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "sci_tech\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "entertainment\n",
      "sci_tech\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "business\n",
      "entertainment\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "sport\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "sci_tech\n",
      "business\n",
      "business\n",
      "sport\n",
      "business\n",
      "business\n",
      "business\n",
      "business\n",
      "entertainment\n",
      "business\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "sci_tech\n",
      "business\n",
      "business\n",
      "sport\n",
      "business\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "us\n",
      "business\n",
      "business\n",
      "business\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "business\n",
      "business\n",
      "entertainment\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "world\n",
      "sport\n",
      "sport\n",
      "health\n",
      "business\n",
      "world\n",
      "sport\n",
      "health\n",
      "business\n",
      "sport\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "sport\n",
      "us\n",
      "business\n",
      "sport\n",
      "world\n",
      "health\n",
      "sport\n",
      "sport\n",
      "world\n",
      "sport\n",
      "business\n",
      "sport\n",
      "business\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "health\n",
      "business\n",
      "us\n",
      "health\n",
      "business\n",
      "entertainment\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "health\n",
      "business\n",
      "us\n",
      "business\n",
      "world\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "sport\n",
      "us\n",
      "entertainment\n",
      "us\n",
      "business\n",
      "business\n",
      "entertainment\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "business\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "health\n",
      "entertainment\n",
      "sci_tech\n",
      "health\n",
      "business\n",
      "us\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "us\n",
      "us\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "sci_tech\n",
      "us\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sci_tech\n",
      "sport\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "health\n",
      "business\n",
      "sci_tech\n",
      "world\n",
      "business\n",
      "business\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "business\n",
      "sport\n",
      "sport\n",
      "world\n",
      "sport\n",
      "business\n",
      "world\n",
      "world\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "us\n",
      "sport\n",
      "business\n",
      "world\n",
      "us\n",
      "us\n",
      "entertainment\n",
      "us\n",
      "health\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "sci_tech\n",
      "business\n",
      "business\n",
      "sport\n",
      "business\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "entertainment\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "world\n",
      "health\n",
      "business\n",
      "world\n",
      "business\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "us\n",
      "world\n",
      "entertainment\n",
      "world\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "business\n",
      "world\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "us\n",
      "sport\n",
      "sci_tech\n",
      "sci_tech\n",
      "sport\n",
      "world\n",
      "business\n",
      "sport\n",
      "us\n",
      "sport\n",
      "health\n",
      "health\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "sci_tech\n",
      "entertainment\n",
      "world\n",
      "entertainment\n",
      "sci_tech\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "business\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "sci_tech\n",
      "business\n",
      "sci_tech\n",
      "world\n",
      "world\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "business\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "us\n",
      "entertainment\n",
      "business\n",
      "sport\n",
      "sport\n",
      "us\n",
      "world\n",
      "us\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "business\n",
      "sport\n",
      "world\n",
      "world\n",
      "us\n",
      "business\n",
      "entertainment\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "sport\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "world\n",
      "business\n",
      "us\n",
      "world\n",
      "business\n",
      "sport\n",
      "world\n",
      "us\n",
      "sport\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "us\n",
      "world\n",
      "us\n",
      "sport\n",
      "sport\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "world\n",
      "world\n",
      "world\n",
      "us\n",
      "sport\n",
      "sport\n",
      "us\n",
      "world\n",
      "sport\n",
      "business\n",
      "us\n",
      "sci_tech\n",
      "business\n",
      "us\n",
      "business\n",
      "health\n",
      "entertainment\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "business\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "us\n",
      "world\n",
      "business\n",
      "sport\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "health\n",
      "us\n",
      "world\n",
      "entertainment\n",
      "entertainment\n",
      "world\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "sci_tech\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "sport\n",
      "business\n",
      "us\n",
      "business\n",
      "sport\n",
      "business\n",
      "world\n",
      "business\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "health\n",
      "world\n",
      "entertainment\n",
      "us\n",
      "business\n",
      "us\n",
      "world\n",
      "health\n",
      "entertainment\n",
      "us\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "world\n",
      "world\n",
      "business\n",
      "health\n",
      "us\n",
      "sci_tech\n",
      "health\n",
      "sport\n",
      "business\n",
      "world\n",
      "us\n",
      "business\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "business\n",
      "world\n",
      "world\n",
      "sport\n",
      "health\n",
      "business\n",
      "world\n",
      "business\n",
      "world\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "business\n",
      "world\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "business\n",
      "sport\n",
      "world\n",
      "us\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "health\n",
      "business\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "business\n",
      "world\n",
      "us\n",
      "sci_tech\n",
      "sci_tech\n",
      "us\n",
      "business\n",
      "world\n",
      "us\n",
      "world\n",
      "world\n",
      "us\n",
      "sport\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "health\n",
      "sport\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "us\n",
      "sport\n",
      "us\n",
      "sport\n",
      "us\n",
      "world\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "world\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "health\n",
      "sport\n",
      "world\n",
      "business\n",
      "sport\n",
      "world\n",
      "sport\n",
      "us\n",
      "sport\n",
      "us\n",
      "us\n",
      "sport\n",
      "business\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "health\n",
      "world\n",
      "business\n",
      "sport\n",
      "world\n",
      "business\n",
      "entertainment\n",
      "business\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "sport\n",
      "health\n",
      "sci_tech\n",
      "entertainment\n",
      "health\n",
      "entertainment\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "business\n",
      "world\n",
      "health\n",
      "business\n",
      "us\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "world\n",
      "health\n",
      "business\n",
      "world\n",
      "world\n",
      "us\n",
      "business\n",
      "world\n",
      "us\n",
      "sport\n",
      "sport\n",
      "world\n",
      "world\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "sport\n",
      "sport\n",
      "us\n",
      "business\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "world\n",
      "world\n",
      "sport\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "world\n",
      "business\n",
      "business\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "health\n",
      "us\n",
      "sport\n",
      "sport\n",
      "us\n",
      "sci_tech\n",
      "us\n",
      "sport\n",
      "business\n",
      "health\n",
      "world\n",
      "health\n",
      "business\n",
      "world\n",
      "sport\n",
      "world\n",
      "world\n",
      "world\n",
      "sci_tech\n",
      "entertainment\n",
      "health\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "business\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "world\n",
      "us\n",
      "business\n",
      "business\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "world\n",
      "us\n",
      "us\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "entertainment\n",
      "us\n",
      "business\n",
      "business\n",
      "sci_tech\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "world\n",
      "business\n",
      "sport\n",
      "us\n",
      "sport\n",
      "business\n",
      "sport\n",
      "world\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "us\n",
      "sci_tech\n",
      "sport\n",
      "sport\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "sport\n",
      "health\n",
      "us\n",
      "us\n",
      "us\n",
      "world\n",
      "business\n",
      "us\n",
      "sci_tech\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "sport\n",
      "sport\n",
      "us\n",
      "us\n",
      "health\n",
      "world\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "sport\n",
      "us\n",
      "world\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "business\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "us\n",
      "world\n",
      "business\n",
      "sport\n",
      "sport\n",
      "us\n",
      "sci_tech\n",
      "entertainment\n",
      "world\n",
      "world\n",
      "sport\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "business\n",
      "sport\n",
      "business\n",
      "sport\n",
      "sci_tech\n",
      "world\n",
      "business\n",
      "sport\n",
      "us\n",
      "business\n",
      "world\n",
      "sport\n",
      "sport\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "business\n",
      "sci_tech\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "health\n",
      "entertainment\n",
      "entertainment\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "sci_tech\n",
      "sci_tech\n",
      "world\n",
      "sport\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "business\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "us\n",
      "sport\n",
      "us\n",
      "sport\n",
      "entertainment\n",
      "health\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "business\n",
      "health\n",
      "business\n",
      "business\n",
      "business\n",
      "business\n",
      "sci_tech\n",
      "world\n",
      "us\n",
      "entertainment\n",
      "sci_tech\n",
      "sport\n",
      "sci_tech\n",
      "sport\n",
      "business\n",
      "sci_tech\n",
      "entertainment\n",
      "business\n",
      "business\n",
      "sport\n",
      "world\n",
      "world\n",
      "business\n",
      "sci_tech\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "us\n",
      "sport\n",
      "business\n",
      "world\n",
      "us\n",
      "sport\n",
      "sport\n",
      "us\n",
      "us\n",
      "sport\n",
      "us\n",
      "us\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "business\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "entertainment\n",
      "us\n",
      "us\n",
      "business\n",
      "world\n",
      "business\n",
      "entertainment\n",
      "sport\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "entertainment\n",
      "entertainment\n",
      "business\n",
      "health\n",
      "business\n",
      "sport\n",
      "health\n",
      "health\n",
      "sport\n",
      "sci_tech\n",
      "health\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "us\n",
      "business\n",
      "world\n",
      "health\n",
      "sport\n",
      "sport\n",
      "us\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "health\n",
      "sport\n",
      "entertainment\n",
      "world\n",
      "sci_tech\n",
      "us\n",
      "us\n",
      "us\n",
      "world\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "sport\n",
      "business\n",
      "sport\n",
      "sport\n",
      "business\n",
      "world\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "health\n",
      "entertainment\n",
      "world\n",
      "us\n",
      "sci_tech\n",
      "sport\n",
      "world\n",
      "world\n",
      "world\n",
      "world\n",
      "sport\n",
      "entertainment\n",
      "health\n",
      "entertainment\n",
      "business\n",
      "sci_tech\n",
      "sport\n",
      "us\n",
      "sport\n",
      "us\n",
      "entertainment\n",
      "health\n",
      "sport\n",
      "sport\n",
      "world\n",
      "entertainment\n",
      "business\n",
      "us\n",
      "world\n",
      "world\n",
      "business\n",
      "world\n",
      "world\n",
      "entertainment\n",
      "world\n",
      "sci_tech\n",
      "world\n",
      "sci_tech\n",
      "business\n",
      "world\n",
      "business\n",
      "sport\n",
      "business\n",
      "health\n",
      "entertainment\n",
      "sport\n",
      "sport\n",
      "entertainment\n",
      "sport\n",
      "us\n",
      "us\n",
      "us\n",
      "entertainment\n",
      "world\n",
      "sport\n",
      "sport\n",
      "world\n",
      "business\n",
      "sci_tech\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-89a51d6490ff>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mnews_item\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mnews\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m         \u001b[0mlines\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnews_item\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msplit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"\\n\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlines\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m6\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      8\u001b[0m         \u001b[0mfile_to_write\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'data/'\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mlines\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m6\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'/'\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcount\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlines\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m6\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'.txt'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'w+'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      9\u001b[0m         \u001b[0mcount\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlines\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m6\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcount\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mlines\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m6\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "with open('news', 'r') as f:\n",
    "    text = f.read()\n",
    "    news = text.split(\"\\n\\n\")\n",
    "    count = {'sport': 0, 'world': 0, \"us\": 0, \"business\": 0, \"health\": 0, \"entertainment\": 0, \"sci_tech\": 0}\n",
    "    for news_item in news:\n",
    "        lines = news_item.split(\"\\n\")\n",
    "        print(lines[6])\n",
    "        file_to_write = open('data/' + lines[6] + '/' + str(count[lines[6]]) + '.txt', 'w+')\n",
    "        count[lines[6]] = count[lines[6]] + 1\n",
    "        file_to_write.write(news_item)  # python will convert \\n to os.linesep\n",
    "        file_to_write.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'data': \"court agrees to expedite n.f.l.'s appeal the decision means a ruling could be made nearly two months before the regular season begins, time for the sides to work out a deal without delaying the season.\",\n",
       " 'flag': 0}"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas\n",
    "import glob\n",
    "\n",
    "category_list = [\"sport\", \"world\", \"us\", \"business\", \"health\", \"entertainment\", \"sci_tech\"]\n",
    "directory_list = [\"data/sport/*.txt\", \"data/world/*.txt\",\"data/us/*.txt\",\"data/business/*.txt\",\"data/health/*.txt\",\"data/entertainment/*.txt\",\"data/sci_tech/*.txt\",]\n",
    "\n",
    "text_files = list(map(lambda x: glob.glob(x), directory_list))\n",
    "text_files = [item for sublist in text_files for item in sublist]\n",
    "\n",
    "training_data = []\n",
    "\n",
    "\n",
    "for t in text_files:\n",
    "    f = open(t, 'r')\n",
    "    f = f.read()\n",
    "    t = f.split('\\n')\n",
    "    training_data.append({'data' : t[0] + ' ' + t[1], 'flag' : category_list.index(t[6])})\n",
    "    \n",
    "training_data[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1433,)\n"
     ]
    }
   ],
   "source": [
    "training_data = pandas.DataFrame(training_data, columns=['data', 'flag'])\n",
    "training_data.to_csv(\"train_data.csv\", sep=',', encoding='utf-8')\n",
    "print(training_data.data.shape)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pickle\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "\n",
    "\n",
    "#GET VECTOR COUNT\n",
    "count_vect = CountVectorizer()\n",
    "X_train_counts = count_vect.fit_transform(training_data.data)\n",
    "\n",
    "#SAVE WORD VECTOR\n",
    "pickle.dump(count_vect.vocabulary_, open(\"count_vector.pkl\",\"wb\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from sklearn.feature_extraction.text import TfidfTransformer\n",
    "\n",
    "#TRANSFORM WORD VECTOR TO TF IDF\n",
    "tfidf_transformer = TfidfTransformer()\n",
    "X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)\n",
    "\n",
    "#SAVE TF-IDF\n",
    "pickle.dump(tfidf_transformer, open(\"tfidf.pkl\",\"wb\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Multinomial Naive Bayes\n",
    "\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "#clf = MultinomialNB().fit(X_train_tfidf, training_data.flag)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, training_data.flag, test_size=0.25, random_state=42)\n",
    "clf = MultinomialNB().fit(X_train, y_train)\n",
    "\n",
    "#SAVE MODEL\n",
    "pickle.dump(clf, open(\"nb_model.pkl\", \"wb\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sport\n"
     ]
    }
   ],
   "source": [
    "import pickle\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.feature_extraction.text import TfidfTransformer\n",
    "\n",
    "category_list = [\"sport\", \"world\", \"us\", \"business\", \"health\", \"entertainment\", \"sci_tech\"]\n",
    "\n",
    "docs_new = \"Messi joins other football team\"\n",
    "docs_new = [docs_new]\n",
    "\n",
    "#LOAD MODEL\n",
    "loaded_vec = CountVectorizer(vocabulary=pickle.load(open(\"count_vector.pkl\", \"rb\")))\n",
    "loaded_tfidf = pickle.load(open(\"tfidf.pkl\",\"rb\"))\n",
    "loaded_model = pickle.load(open(\"nb_model.pkl\",\"rb\"))\n",
    "\n",
    "X_new_counts = loaded_vec.transform(docs_new)\n",
    "X_new_tfidf = loaded_tfidf.transform(X_new_counts)\n",
    "predicted = loaded_model.predict(X_new_tfidf)\n",
    "\n",
    "print(category_list[predicted[0]])\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "world  -  world\n",
      "sport  -  world\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  sci_tech\n",
      "business  -  business\n",
      "sport  -  entertainment\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  health\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "world  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  entertainment\n",
      "sport  -  us\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  us\n",
      "business  -  business\n",
      "sport  -  health\n",
      "sport  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  health\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "sport  -  health\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "sport  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sci_tech\n",
      "world  -  us\n",
      "sport  -  business\n",
      "sport  -  sci_tech\n",
      "sport  -  sci_tech\n",
      "sport  -  us\n",
      "sport  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  entertainment\n",
      "sport  -  health\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  sci_tech\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  health\n",
      "world  -  us\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sci_tech\n",
      "sport  -  entertainment\n",
      "sport  -  us\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  business\n",
      "business  -  business\n",
      "business  -  us\n",
      "world  -  world\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "world  -  world\n",
      "world  -  health\n",
      "sport  -  sport\n",
      "world  -  us\n",
      "business  -  health\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sport  -  entertainment\n",
      "sport  -  health\n",
      "world  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sci_tech\n",
      "sport  -  us\n",
      "sport  -  us\n",
      "business  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "world  -  world\n",
      "business  -  entertainment\n",
      "sport  -  entertainment\n",
      "world  -  us\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  business\n",
      "world  -  world\n",
      "world  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  health\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  entertainment\n",
      "sport  -  sci_tech\n",
      "sport  -  us\n",
      "sport  -  health\n",
      "business  -  business\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "sport  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  sci_tech\n",
      "sport  -  entertainment\n",
      "world  -  business\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "business  -  entertainment\n",
      "sport  -  health\n",
      "world  -  sci_tech\n",
      "sport  -  entertainment\n",
      "sport  -  us\n",
      "business  -  business\n",
      "world  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  business\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  sci_tech\n",
      "world  -  world\n",
      "sport  -  health\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  health\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  business\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  health\n",
      "sport  -  entertainment\n",
      "sport  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  world\n",
      "business  -  business\n",
      "business  -  world\n",
      "world  -  world\n",
      "sport  -  sci_tech\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  business\n",
      "sport  -  us\n",
      "sport  -  world\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "sport  -  sci_tech\n",
      "world  -  business\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  sci_tech\n",
      "us  -  health\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "world  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "business  -  sci_tech\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "sport  -  health\n",
      "sport  -  business\n",
      "sport  -  business\n",
      "sport  -  us\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  health\n",
      "world  -  health\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  world\n",
      "sport  -  world\n",
      "sport  -  sport\n",
      "sport  -  sci_tech\n",
      "sport  -  us\n",
      "business  -  business\n",
      "sport  -  us\n",
      "world  -  sci_tech\n",
      "business  -  sci_tech\n",
      "sport  -  health\n",
      "world  -  world\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  health\n",
      "sport  -  world\n",
      "sport  -  health\n",
      "sport  -  health\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "business  -  business\n",
      "sport  -  entertainment\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "world  -  us\n",
      "sport  -  sport\n",
      "sport  -  business\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n"
     ]
    }
   ],
   "source": [
    "predicted = loaded_model.predict(X_test)\n",
    "result_bayes = pandas.DataFrame( {'true_labels': y_test,'predicted_labels': predicted})\n",
    "result_bayes.to_csv('res_bayes.csv', sep = ',')\n",
    "\n",
    "for predicted_item, result in zip(predicted, y_test):\n",
    "    print(category_list[predicted_item], ' - ', category_list[result])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[86  1  0  0  0  0  0]\n",
      " [ 6 66  0  1  0  0  0]\n",
      " [29  7  3  2  0  0  0]\n",
      " [17  3  0 46  0  0  0]\n",
      " [18  2  1  2  0  0  0]\n",
      " [32  1  0  3  0  4  0]\n",
      " [17  4  0  8  0  0  0]]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix  \n",
    "\n",
    "confusion_mat = confusion_matrix(y_test,predicted)\n",
    "print(confusion_mat)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,\n",
       "       beta_2=0.999, early_stopping=False, epsilon=1e-08,\n",
       "       hidden_layer_sizes=(15,), learning_rate='constant',\n",
       "       learning_rate_init=0.001, max_iter=200, momentum=0.9,\n",
       "       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,\n",
       "       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,\n",
       "       warm_start=False)"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.neural_network import MLPClassifier\n",
    "\n",
    "clf_neural = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15,), random_state=1)\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, training_data.flag, test_size=0.25, random_state=42)\n",
    "\n",
    "clf_neural.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "pickle.dump(clf_neural, open(\"softmax.pkl\", \"wb\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "world  -  world\n",
      "health  -  world\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "health  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "health  -  sci_tech\n",
      "business  -  business\n",
      "health  -  entertainment\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "us  -  world\n",
      "health  -  entertainment\n",
      "health  -  sport\n",
      "business  -  world\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "sci_tech  -  health\n",
      "sport  -  sport\n",
      "health  -  sci_tech\n",
      "sport  -  sport\n",
      "health  -  entertainment\n",
      "business  -  business\n",
      "us  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "health  -  business\n",
      "sci_tech  -  entertainment\n",
      "world  -  world\n",
      "world  -  sport\n",
      "sport  -  sport\n",
      "sport  -  us\n",
      "sport  -  sport\n",
      "health  -  us\n",
      "entertainment  -  entertainment\n",
      "health  -  us\n",
      "world  -  world\n",
      "business  -  business\n",
      "health  -  business\n",
      "us  -  us\n",
      "business  -  business\n",
      "health  -  health\n",
      "health  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "health  -  sport\n",
      "world  -  world\n",
      "health  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  business\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "health  -  business\n",
      "health  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "sci_tech  -  sci_tech\n",
      "world  -  us\n",
      "health  -  business\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "sport  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "health  -  entertainment\n",
      "health  -  health\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "health  -  entertainment\n",
      "us  -  entertainment\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  health\n",
      "us  -  us\n",
      "health  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sci_tech\n",
      "health  -  entertainment\n",
      "business  -  us\n",
      "health  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "health  -  business\n",
      "health  -  business\n",
      "business  -  us\n",
      "health  -  world\n",
      "health  -  entertainment\n",
      "health  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "health  -  sport\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "world  -  world\n",
      "health  -  health\n",
      "health  -  sport\n",
      "us  -  us\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "health  -  entertainment\n",
      "health  -  health\n",
      "health  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "us  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sci_tech\n",
      "health  -  us\n",
      "sport  -  us\n",
      "health  -  entertainment\n",
      "sport  -  sport\n",
      "health  -  sport\n",
      "entertainment  -  entertainment\n",
      "health  -  business\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  world\n",
      "us  -  entertainment\n",
      "entertainment  -  entertainment\n",
      "health  -  us\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "us  -  world\n",
      "health  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "health  -  us\n",
      "health  -  health\n",
      "world  -  world\n",
      "us  -  us\n",
      "health  -  entertainment\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  us\n",
      "health  -  health\n",
      "business  -  business\n",
      "sci_tech  -  entertainment\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "sport  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  sci_tech\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sci_tech  -  entertainment\n",
      "health  -  business\n",
      "health  -  entertainment\n",
      "health  -  health\n",
      "health  -  sci_tech\n",
      "health  -  entertainment\n",
      "us  -  us\n",
      "health  -  business\n",
      "health  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "health  -  business\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "world  -  world\n",
      "health  -  health\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "health  -  entertainment\n",
      "health  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "health  -  health\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "health  -  business\n",
      "health  -  entertainment\n",
      "sport  -  sport\n",
      "health  -  health\n",
      "health  -  entertainment\n",
      "us  -  business\n",
      "sci_tech  -  business\n",
      "sport  -  sport\n",
      "health  -  business\n",
      "health  -  world\n",
      "business  -  business\n",
      "business  -  world\n",
      "health  -  world\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "health  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "health  -  business\n",
      "sport  -  us\n",
      "entertainment  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "us  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "business  -  sci_tech\n",
      "sci_tech  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "world  -  sport\n",
      "world  -  world\n",
      "sci_tech  -  sci_tech\n",
      "us  -  health\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "us  -  world\n",
      "business  -  business\n",
      "health  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sci_tech  -  sport\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "health  -  health\n",
      "sci_tech  -  business\n",
      "health  -  business\n",
      "health  -  us\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "health  -  sport\n",
      "sport  -  sport\n",
      "health  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "us  -  us\n",
      "health  -  health\n",
      "world  -  health\n",
      "world  -  world\n",
      "world  -  world\n",
      "us  -  us\n",
      "us  -  world\n",
      "us  -  world\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "us  -  us\n",
      "business  -  business\n",
      "us  -  us\n",
      "world  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "health  -  health\n",
      "world  -  world\n",
      "business  -  us\n",
      "sport  -  sport\n",
      "sport  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  health\n",
      "world  -  world\n",
      "health  -  health\n",
      "health  -  health\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "health  -  us\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "business  -  sci_tech\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "sci_tech  -  business\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n"
     ]
    }
   ],
   "source": [
    "predicted = clf_neural.predict(X_test)\n",
    "result_softmax = pandas.DataFrame( {'true_labels': y_test,'predicted_labels': predicted})\n",
    "result_softmax.to_csv('res_softmax.csv', sep = ',')\n",
    "\n",
    "for predicted_item, result in zip(predicted, y_test):\n",
    "    print(category_list[predicted_item], ' - ', category_list[result])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from sklearn import svm\n",
    "clf_svm = svm.LinearSVC()\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, training_data.flag, test_size=0.25, random_state=42)\n",
    "clf_svm.fit(X_train_tfidf, training_data.flag)\n",
    "pickle.dump(clf_svm, open(\"svm.pkl\", \"wb\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "world  -  world\n",
      "world  -  world\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "us  -  us\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "us  -  us\n",
      "business  -  business\n",
      "health  -  health\n",
      "us  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "business  -  business\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "health  -  health\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "world  -  world\n",
      "world  -  world\n",
      "health  -  health\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sci_tech  -  sci_tech\n",
      "entertainment  -  entertainment\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "business  -  business\n",
      "us  -  us\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "world  -  world\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "health  -  health\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "health  -  health\n",
      "us  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "entertainment  -  entertainment\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "health  -  health\n",
      "world  -  world\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "health  -  health\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sci_tech  -  sci_tech\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "health  -  health\n",
      "sci_tech  -  sci_tech\n",
      "entertainment  -  entertainment\n",
      "us  -  us\n",
      "business  -  business\n",
      "us  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "world  -  world\n",
      "health  -  health\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "us  -  us\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "health  -  health\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "health  -  health\n",
      "entertainment  -  entertainment\n",
      "business  -  business\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "business  -  business\n",
      "us  -  us\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "sci_tech  -  sci_tech\n",
      "health  -  health\n",
      "business  -  business\n",
      "business  -  business\n",
      "world  -  world\n",
      "world  -  world\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "world  -  world\n",
      "business  -  business\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "health  -  health\n",
      "business  -  business\n",
      "business  -  business\n",
      "us  -  us\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "world  -  world\n",
      "us  -  us\n",
      "health  -  health\n",
      "health  -  health\n",
      "world  -  world\n",
      "world  -  world\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "business  -  business\n",
      "us  -  us\n",
      "sci_tech  -  sci_tech\n",
      "sci_tech  -  sci_tech\n",
      "health  -  health\n",
      "world  -  world\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "entertainment  -  entertainment\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "sport  -  sport\n",
      "health  -  health\n",
      "world  -  world\n",
      "health  -  health\n",
      "health  -  health\n",
      "world  -  world\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "business  -  business\n",
      "entertainment  -  entertainment\n",
      "sport  -  sport\n",
      "sci_tech  -  sci_tech\n",
      "us  -  us\n",
      "sport  -  sport\n",
      "business  -  business\n",
      "sport  -  sport\n",
      "us  -  us\n",
      "world  -  world\n",
      "world  -  world\n"
     ]
    }
   ],
   "source": [
    "predicted = clf_svm.predict(X_test)\n",
    "result_svm = pandas.DataFrame( {'true_labels': y_test,'predicted_labels': predicted})\n",
    "result_svm.to_csv('res_svm.csv', sep = ',')\n",
    "for predicted_item, result in zip(predicted, y_test):\n",
    "    print(category_list[predicted_item], ' - ', category_list[result])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
